### ISSUE TITLE
Git instructions on developer page

### ISSUE THREAD

**Issue by lfelipe** [KiCad/kicad-website#106]
Folks, git-bzr is no longer available under Fedora, having been replaced by git-remote-bzr. This package is also available on Ubuntu, and is a different script than the one you are currently referencing. 

I started doing the changes to reflect this on the page, but ended up with a glaring problem: git-remote-bzr does not allow you to push to a non-existant branch in bzr (as done in the example).

Suggestion to either change everything over to git-remote-bzr to have a unified setup and try to get them to add this feature while documenting a workaround, or to document the install process of git-bzr-ng on Fedora.

I can do either of those, but would be good to know if there are preferences.

**Comment by nickoe** [comment]
I think we should wait with this, there is discussion of moving entirely to git and then this will not be of any use anyway.

**Comment by nickoe** [comment]
We moved to git now, I will close this issue. Updated instructions was added in ce0f9cdfd1d6d68db8eb8e1dcceaecf692ec31c2.
