### ISSUE TITLE
add gentoo

### ISSUE THREAD

**Issue by jonasstein** [KiCad/kicad-website#108]
Please add a link to the official gentoo package too:
https://packages.gentoo.org/packages/sci-electronics/kicad

install with:
# emerge sci-electronics/kicad

**Comment by nickoe** [comment]
sure, but please note http://kicad-pcb.org/post/release-4.0.1/

**Comment by jonasstein** [comment]
thank you. We already marked kicad for a version bump to 4.0.1 in the gentoo repository. https://bugs.gentoo.org/show_bug.cgi?id=568088

**Comment by marekr** [comment]
So it turns out the font we use to render the download icons (https://github.com/Lukas-W/font-linux) doesn't have gentoo.......and I don't really want to put an image :/

**Comment by nickoe** [comment]
Yeah, I know. I tried to update the font with the tool used to generate the font I hit some problems running it, related to font forge.

**Comment by Caerbannog** [comment]
I have a pull request I'm working on for the Gentoo logo, hang tight:
https://github.com/Lukas-W/font-linux/pull/7

**Comment by Caerbannog** [comment]
A new release of font-linux is available with the Gentoo icon:
https://github.com/Lukas-W/font-linux/releases/tag/v0.2

**Comment by nickoe** [comment]
I have not updated to font-linux 0.2 with 20824789f230c45837346dcd7d72faa86f0cc2fe.
