### ISSUE TITLE
Spanish KiCad translation an forum

### ISSUE THREAD

**Issue by ElektroQuark** [KiCad/kicad-website#132]
Hello,

A couple of notes...

- The KiCad Spanish translation was featured on hackaday.com (first message
ever in Spanish on hackaday). Maybe it is of interest to publish it on the
KiCad webpage in the (DISCOVER->IN THE MEDIA) section.

Link:
http://hackaday.com/2016/02/11/kicad-traducido-al-espanol/

- There has been some interest among some users about a Spanish forum about
KiCad, so I published one here: www.elektroquark.com/forokicad. It's
starting now but, could it be linked from the COMMUNITY section?

Best regards.

**Comment by nickoe** [comment]
Theese two point have been added to the site alread. Closing.
