### ISSUE TITLE
Version control system still bzr on contribute page

### ISSUE THREAD

**Issue by MichaelKavanagh** [KiCad/kicad-website#168]
Hi,
Instructions on the developers contribute page ([http://kicad-pcb.org/contribute/developers/](http://kicad-pcb.org/contribute/developers/)) still show the instructions for setting up Bazaar, despite the official switch to git [(http://kicad-pcb.org/post/git-announcement/)](http://kicad-pcb.org/post/git-announcement/).

**Comment by nickoe** [comment]
This was fixed with pull request #170 in ce0f9cdfd1d6d68db8eb8e1dcceaecf692ec31c2
