### ISSUE TITLE
Debian build instructions don't mention dependencies for scripting

### ISSUE THREAD

**Issue by cpavlina** [KiCad/kicad-website#175]
The build instructions at the bottom of http://kicad-pcb.org/download/debian/ do not list dependencies for scripting (swig, wxpython), nor mention the possibility of enabling scripting when building. I think the official Debian builds might omit that? We should still include it in our own build instructions though, it's an official part of KiCad.

**Comment by marekr** [comment]
@cpavlina Why not put it into the kicad-source doc to keep it centralized? It has the super general instructions in it but I don't see why it doesn't have linux specific.
