### ISSUE TITLE
Installation error Windows 7 32bit

### ISSUE THREAD

**Issue by marquesg** [KiCad/kicad-website#179]
After downloading KiCad for Windows 32bit computer I try to install and get an error message. 
![error](https://cloud.githubusercontent.com/assets/23170059/19856375/651436ec-9f36-11e6-99da-20894933dafd.PNG)
I have tried installing on 2 different 32 bit PC's and get same result.

**Comment by nickoe** [comment]
Have you tried to download this again? And which exact installer did you use?

**Comment by marquesg** [comment]
Yes the first time I downloaded last week and got that error so I tried downloading again this morning and still had problem. I’m not sure what installer I’m using how would I be able to tell?

Marques Garrett

Email: marquesg@maplesystems.com<mailto:marquesg@maplesystems.com>
Website: www.maplesystems.com
[signature-82016]

**Comment by nickoe** [comment]
Ok, I guesd that you clicked on the link  on the website. That points to the 4.0.4 stable release. It installs fine on my win7 system. Could you check the file size? It says 286348 KB or 279 MB on my system.

**Comment by marquesg** [comment]
I have attached the fine that downloads when I click on the 32 bit version. Its 232 KB.

Marques Garrett

Email: marquesg@maplesystems.com<mailto:marquesg@maplesystems.com>
Website: www.maplesystems.com
[signature-82016]

**Comment by nickoe** [comment]
If it is only 232 KB it is clearly a bad download. It seems to me like ypu have some bad connectivity near you or a wonky company proxy.

**Comment by marquesg** [comment]
Well do you know where I can get a good copy?

Marques Garrett

Email: marquesg@maplesystems.com<mailto:marquesg@maplesystems.com>
Website: www.maplesystems.com
[signature-82016]

**Comment by nickoe** [comment]
As a start you could try to see if you can actually download the 64-bit version, or if that also fails. 

Alternatively you can try to download from this mirror  at http://www2.futureware.at/~nickoe/kicad-downloads-mirror/windows/stable/
