### ISSUE TITLE
rusefi for "made with kicad"

### ISSUE THREAD

**Issue by rusefi** [KiCad/kicad-website#185]
Would it be possible to add www.rusefi.com to "made with kicad" list?

rusefi is an open source (automotive) engine control unit, both firmware and kicad hardware are available at https://github.com/rusefi/rusefi

The nicest HW picture is http://rusefi.com/wiki/images/f/f5/Frankenso_top-isometric_notes.png from http://rusefi.com/wiki/index.php?title=Manual:Hardware_Frankenso_board

**Comment by nickoe** [comment]
@rusefi Are you going to migrate from sf.net to github or will you just have github as a mirror?

**Comment by rusefi** [comment]
For now staying with SF - https://sourceforge.net/projects/rusefi/

**Comment by nickoe** [comment]
Since the images is going to be farily small on the page, I would like an image where there is no descriptive text on it if possible. I tried to open the project, but it looks like many 3D models are not existing for me. Do you know if they are available elsewhere?

**Comment by rusefi** [comment]
I suspect some models are the casualty of the older Kicad to newer Kicad migration :( Do you have the ../rusefl_lib folder downloaded?

Will ask the Kicad guy if he can make one or has one.

there is also https://svn.code.sf.net/p/rusefi/code/trunk/hardware/frankenso/frankenso_top.png

**Comment by rusefi** [comment]
PS: also just recovered an older version of https://svn.code.sf.net/p/rusefi/code/trunk/hardware/frankenso/frankenso_top-isometric.png

**Comment by nickoe** [comment]
I choose to add the old image because it had the 3D models populated.

**Comment by rusefi** [comment]
Thank you!
