### ISSUE TITLE
Documentation and website are unreadable

### ISSUE THREAD

**Issue by jimmmmmm** [KiCad/kicad-website#186]
The KiCad PDF documents (March 2, 2016) as well as the web site are a faint gray
and very difficult to read. I can use an add-on to fix the web pages but I'm finding
the PDFs a show-stopper to picking up KiCad.

I know that projects like KiCad take accessibility issues seriously and that they can 
often be difficult to work out but this one is very simple to get right.

I'll refer to the W3.org Web Content Accessibility Guidelines as a helpful reference:
[https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/visual-audio-contrast-contrast.html](url)

> **1.4.3 Contrast (Minimum):** The visual presentation of text and images of text has 
> a contrast ratio of at least 4.5:1

Thanks for your consideration. This would be a big help.

**Comment by marekr** [comment]
I'm failing to see the faint gray on the website. Can you provide a screenshot? The font color here is nowhere near what's considered faint
http://i.imgur.com/gBEbCLW.png

**Comment by nickoe** [comment]
No feedback from OP. Closing.
