### ISSUE TITLE
Dependencies for building with debian

### ISSUE THREAD

**Issue by cedricboudinet** [KiCad/kicad-website#193]
Hello
A dependency is missing for building from source with debian : libboost-test-dev is required but not mentionned in http://kicad-pcb.org/download/debian/

**Comment by marekr** [comment]
Fixed in a688ac93

@nickoe I'm not a fan of the build instructions where they are on the downloads page...and then linking to more build instructions externally....maybe we should put the extra details in the main repo docs?

**Comment by nickoe** [comment]
@marekr, yes, I think they belong in the devdocs. I don't remember why they were added on the debian page at the time being. I think that was the sanest thing to do, but as a temporary solution.
