### ISSUE TITLE
Chromebook?

### ISSUE THREAD

**Issue by Kirball** [KiCad/kicad-website#209]
Has anyone successfully ported this to chromebook?

**Comment by marekr** [comment]
Chromebook disallows native C++ application so no, its completely unfeasible to port.


Unfortunately this repository is also not the place for these kind of questions.  Communication takes place on the developer mailing list or if you are less inclined to a mailing list, there's a users forum here: https://forum.kicad.info where you could possibly find some assistance. (The most likely answer is most people install Linux on their chromebook).
