### ISSUE TITLE
Edit component footprint

### ISSUE THREAD

**Issue by okyaneka** [KiCad/kicad-website#212]
Errors were encountered loading footprints:
IO_ERROR: http GET command failed
Cannot get/download Zip archive: 'https://codeload.github.com/KiCad/Connectors.pretty/zip/master'
for library path: 'https://github.com/KiCad/Connectors.pretty'.
Reason: 'IO_ERROR: curl_easy_perform()=7: Couldn't connect to server
from kicad_curl_easy.cpp : Perform() : line 92'
from github_plugin.cpp : remoteGetZip() : line 554

**Comment by okyaneka** [comment]
Thanks, Solved. I was using proxy

**Comment by marekr** [comment]
@okyaneka Next time please try https://forum.kicad.info/

This github repository is only for the website and not kicad.
