### ISSUE TITLE
Request for site listing

### ISSUE THREAD

**Issue by Flat-earth-academy** [KiCad/kicad-website#217]
I am hoping that you will deem...

http://KicadHowTo.com

... valid to be listed at...

http://kicad-pcb.org/community/sites/

**Comment by poeschlr** [comment]
The screenshots on that side look like they are taken in the pre kicad v4 version. (Version from 2011) Is this side still updated?

**Comment by sbts** [comment]
Yeah, most of that info was generated based on version.... 
`KiCad_stable-2013.07.07-BZR4022_Win_full_version.exe`
downloaded on 07 July 14

I'd vote NO, unless it gets updated to current version UI

**Comment by Flat-earth-academy** [comment]
(From requester)- Yes, the screenshots are old. It only goes into "getting started" issues... like "yes, you should do a schematic first, not try to leap in, do layout "from scratch". Are there issues where something no longer works very much as it did when the bulk of the work on the site was done? (The "new"(-ish!) change in how things are stored in libraries HAS BEEN addressed.)

It's sort of "chicken and egg"... I tend to put the most editing time into the various pages I manage in proportion to the traffic on those sites. If no one knows about KicadHowTo.com, it slips down the list for updates.

**Comment by nickoe** [comment]
Maybe it is more suitable on http://kicad-pcb.org/help/tutorials/?

**Comment by Flat-earth-academy** [comment]
> Maybe it is more suitable on http://kicad-pcb.org/help/tutorials/?

Thank you for that contribution to the discussion. Makes sense to me/ 
would be very welcome, especially as "KiCadHowTo.com from 
SheepdogGuides".

Tom

**Comment by marekr** [comment]
Added in c91b6dc
