### ISSUE TITLE
Downloads page adding a distrobution?

### ISSUE THREAD

**Issue by jcfrosty** [KiCad/kicad-website#218]
Sabayon Linux has kicad in our repository. its simple to install using the GUI Rigo or CLI "equo install kicad".

We'd like to be added to your download page list if possible 👍 

you can take a look at our distro at www.sabayonlinux.org

**Comment by marekr** [comment]
Yea we need a better way to deal with every Linux distro under the sun (wooo fragmented Linux ecosystem). We do a horrible job updating the current distro pages we have listed as is :/

@nickoe any thoughts?

On one hand we can remove version information from the download page altogether which makes this super lazy for us, but on the other, the lol that will happen when 5.0 is released will be annoying.

**Comment by nickoe** [comment]
I don't think we do a horrible job updating it. I have been checking the verions once in a while manually to see if the distro updated to a newer kicad release, but they have usually not. I am ok with keeping the mechanism we have now. It is flexible in the sense that we can easily reflect the differences and get an overview of the state of the kicad releases on different platforms.

**Comment by marekr** [comment]
@nickoe the mint page is out of date :P

**Comment by jcfrosty** [comment]
Sabayon is based on Gentoo, but uses binary packages built from portage
tree, Instead of user compiling from source. Because we're based on Gentoo,
we're pretty bleeding edge.

**Comment by marekr** [comment]
Added in f3cafbf

**Comment by marekr** [comment]
@jcfrosty Hey, why does the sabayon website decide to change the link?

Now the link to the package is
https://packages.sabayon.org/show/kicad,202461,sabayon-weekly,amd64,5,standard

instead of 
https://packages.sabayon.org/show/kicad,199050,sabayon-weekly,amd64,5,standard[


What gives?

**Comment by jcfrosty** [comment]
We recently upgraded GCC and the package was rebuilt resulting in a
different package name (_r1) we also have different repositories. Your link
only shows "Weekly" which is a more stable and delayed update repo. While
the normal repo is sabayonlinux.org, we also have the limbo repo which is
testing. The best link to use would be a search for kicad which brings up
the multiple repos serving.

https://packages.sabayon.org/quicksearch?q=kicad&x=0&y=0

**Comment by jcfrosty** [comment]
Also, I wanted to thank you for keeping up with this and contacting me. I
do appreciate you going through the trouble of adding us to your site
showing our support.

**Comment by marekr** [comment]
Interesting, so there's the site repology.org that provides a service of version badges for distro apps. They claim kicad in sabayon comes from Gentoo and hence they will not provide a sabayon badge?

Any thoughts?

https://repology.org/metapackage/kicad/report

**Comment by jcfrosty** [comment]
Yes Sabayon comes from Gentoo the way SUSE comes from Slackware. It's our
upstream. But that doesn't make us the same. We use binary packages,
portage/Gentoo is source code and compiling. So by this concept, they
should dump Ubuntu because it's a derivative of Debian? It's a
misconception.
