### ISSUE TITLE
wrong version in download

### ISSUE THREAD

**Issue by jonasstein** [KiCad/kicad-website#240]
Hi http://kicad-pcb.org/download/gentoo/: "KiCad 4.0.4 is available in in the official gentoo packages. "
this is wrong, we ship 4.0.7
I suggest just to remove the version number there. We update usually short after release
perhaps also interesting: https://repology.org/metapackage/kicad/versions
or https://repology.org/metapackage/kicad/badges
these update automatically

**Comment by marekr** [comment]
Fixed in be0657a84f0629f4a37b6ab137c1e54b56fa15f9

I wish repology had the correct Ubuntu/Mint repos (we don't advise the upstream) and its missing Sabayon (well it says the repo in sabayon is missing but its not)

**Comment by jonasstein** [comment]
Thank you for the fix.
For Ubuntu and Mint one can see what the distribution ships. This is what the user expects. As bonus you provide external packages, which are newer. For Sabayon it is not so interesting to have an individual version tracker. Sabayon users package constantly what gentoo ships. So a few weeks after Gentoo it is in Sabayon. See "Upstream package" on the bottom left:
https://packages.sabayon.org/show/kicad,202461,sabayon-weekly,amd64,5,standard/#package-widget-show-what
