### ISSUE TITLE
Request to feature KiCad like a Pro [Video] on Tutorials page

### ISSUE THREAD

**Issue by packtpartner** [KiCad/kicad-website#245]
Hi,

We would request you to feature the following Video Tutorial on http://kicad-pcb.org/help/tutorials/ under "Video Tutorials" section. 

**[KiCad like a Pro](
https://www.packtpub.com/hardware-and-creative/kicad-pro-video)** by Peter Dalmaris (~7 hours 36 minutes)

Thanks

**Comment by nickoe** [comment]
I don't see why we should link to this. There is not even a proper preview as it is behind a paywall. The preview features on that site just radiates "fuck off" in the face to every visitor.
