### ISSUE TITLE
feature request   3d pcb view to stl  file export 

### ISSUE THREAD

**Issue by achiestdragon** [KiCad/kicad-website#250]
it seems to be missing the 3d pcb view exportable in a 3d format like  stl  so it can be imported to blender , openscad and other cad packages as its usefull for when creating an enclosure   ie mounting points  cut outs for connectors and such

**Comment by nickoe** [comment]
This repo is for the kicad website itself, bug reports for the kicad program should be reported on launchpad. It is linked in http://kicad-pcb.org/help/report-a-bug/

But you can use the vrml output directly in blender .

**Comment by poeschlr** [comment]
@achiestdragon tools for getting your board over into blender already exist. Have a look over at the forum ;)

Relevant topics:
https://forum.kicad.info/t/blender-kicad-3d-model-export-plugin/3104
https://forum.kicad.info/t/export-pcb-devices-with-textures-for-rendering-in-blender-etc/7490/

For exporting to step (mechanical cad integration) have a look at the kicad stepup extension for freecad. (Allows importing a pcb file into freecad.)
https://forum.kicad.info/t/kicad-stepup-the-sketcher-for-getting-to-blinky/7826
https://forum.kicad.info/t/kicad-stepup-a-new-update/8761
