### ISSUE TITLE
Unable to do apt-get install kicad

### ISSUE THREAD

**Issue by dennis-winz** [KiCad/kicad-website#260]
Have a system on a rockchip ....aarch64 running ubuntu xenial 16.04.3 LTS and can get all of the ancillary packages but cannot do a apt-get install for kicad.  

Error is as follows;
Package kicad is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'kicad' has no installation candidate

Yes I have added this repository to pull from.... 

Hit:1 http://ppa.launchpad.net/js-reynaud/kicad-4/ubuntu xenial InRelease               
Hit:3 http://ppa.launchpad.net/js-reynaud/ppa-kicad/ubuntu xenial InRelease 

According to the package list all the rest are marked "all" and I can get but kicad labeled "arm64" and seems I can't get it. Thank you as I also have armhf and x86 system which all seem to work. I am trying to replace my Eagle systems. This particular one I use as I travel....Normally in NZ.

dennis.winz@gmail.com

**Comment by marekr** [comment]
I believe js-reynaud only provides 32 and 64-bit builds for x86 processors. The issue probably being he has nothing to test with for ARM nor the desire to setup cross compilation which is a whole time consuming adventure with all the dependencies. 

The other packages don't have any executables so there's no problem marking them all.

The only thing I can suggest is you remove the ppa and you use the Ubuntu distro slightly outdated Kicad 4.0.2 for Xenial as Ubuntu themselves maintains an arm64 build there.  Unless you want to build from source.
