### ISSUE TITLE
Redirection from kicad.org is broken

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-website#261]
`http://kicad.org` seems to redirect to `https://kicad-pcb.org` instead of `http://kicad-pcb.org`

**Comment by marekr** [comment]
@nickoe Either we get digikey to fix it or put SSL on kicad :3 We can get letsencrypt setup...

**Comment by antoniovazquezblanco** [comment]
+1 to SSL on KiCad webpage!

**Comment by bombledmonk** [comment]
It's probably a better solution to go the letsencrypt direction.  How do we get it done?

**Comment by nickoe** [comment]
@bombledmonk Thank you!

I guess we can close this issue. Getting https is another ongoing task. It is complicated because of the proxy in between the server and the world.
