### ISSUE TITLE
Some broken links to KLC

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-website#262]
Using a link checker it looks like we have some KLC klinks linking to broken URL's:
http://kicad-pcb.org/klc/S5.2
http://kicad-pcb.org/klc/S4.3
http://kicad-pcb.org/klc/S4.5

These are the ones linked to which are 404, I think they miss libraries in the URL. I reported this because I am not able to fix it right now.

**Comment by nickoe** [comment]
Thanks.

**Comment by larryn46** [comment]
Broken link http://docs.kicad-pcb.org/5.0.0/nl/getting_started_in_kicad.pdf from google search for KiCad 5 tutorial, "KiCad 5 – a new generation | KiCad EDA
kicad-pcb.org/blog/2018/07/KiCad-5--a-new-generation/"
