### ISSUE TITLE
Error changing value, example resistance

### ISSUE THREAD

**Issue by Michrel** [KiCad/kicad-website#273]
I've been drawing small schemas with version 4.07 for a long time, always OK. For some time there is a mistake: I can also change the value of a resistor, or other parts. If I want to continue then sometimes it goes again, then it's over. Save project, close, reopen and you can continue this way, 1 or 2 object. This happens with the Windows 10 version, on the latest version. I have then tried the same project on the Linux machine Mint 18.2, there it works flawlessly. So I can draw the schema on Windows is fine, to determine the values I have to do it on Linux. There is version 4.02, older version.
I translated everything with Google because my English is minimal, I can understand datasheets, but I have to translate a text.
I think the idea of KiCad is good, that's why I reported the error. Is there a job in Germany where you could also report it?
Best regards
Michel
 my Email:   hb9vro@gmail.com

**Comment by eldarkg** [comment]
@Michrel Kicad bugs should be reported here https://bugs.launchpad.net/kicad. This bug tracker contain only kicad website issues.
