### ISSUE TITLE
KiCad - Schematic Grid Size

### ISSUE THREAD

**Issue by Veeralakshmi92** [KiCad/kicad-website#279]
Hi,

I have completed the Schematic in KiCad. Later I have noticed about the Grid Size, it was wrong. I would like to change the Grid Size. But for that I need to redraw the Schematics. Is there any other way to change the Schematic Grid Size rather than doing from the scratch?

Could you please help me to resolve this issue?

**Comment by nickoe** [comment]
You can probably just move things around after you changed it to a finer grid. But this place is not the correct place to ask these questions. This question might be more appropriate on the forum.
