### ISSUE TITLE
Migration information?

### ISSUE THREAD

**Issue by adamwolf** [KiCad/kicad-website#294]
Is there some way we can replace the migration from old stable doc with the new one Wayne wrote?

**Comment by nickoe** [comment]
I don't think we need to replace it. We could just add that this does not apply for migration from 4.0 to 5.0.

**Comment by nickoe** [comment]
We should be aware that this sort of info is also available in http://docs.kicad-pcb.org/master/en/kicad.html#_upgrading_from_version_4_to_version_5

**Comment by marekr** [comment]
Then why don't we move it to the doc and eliminate the website page?

**Comment by marekr** [comment]
Commited  628b97a to clarify it. Old stable info is kept, it just splits the page to have info on where to find v4 to v5 separate from the old old stuff.
