### ISSUE TITLE
S7.1 - "#PWR" --> "#PWR?"?

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [KiCad/kicad-website#317]
https://github.com/KiCad/kicad-website/blob/master/content/klc/S7.1.adoc

Shouldn't it say:
`1. Reference Designator must be set to #PWR?`? (notice the added question mark, just like shown in the image)

Instead of: 
`1. Reference Designator must be set to #PWR`

![image](https://user-images.githubusercontent.com/6842199/43986867-35000fc6-9ccd-11e8-9311-2248ec667185.png)

**Comment by poeschlr** [comment]
The reference field it self for this part has #PWR as its content. (check with right-click edit or shortcut e)

The ? is displayed by the editor to show that there will be numbers added by the annotation algorithm. (Look at any other symbol and you will see it also displays a ?.)

![screenshot from 2018-08-11 10-35-38](https://user-images.githubusercontent.com/18327350/43989885-e760829c-9d52-11e8-9db2-c081a5d25c5f.png)

**Comment by ElectricRCAircraftGuy** [comment]
Thanks! That clarified it for me. I'm doing my first read through the KLC and trying to spot things as I go.
