### ISSUE TITLE
F2.2: Use "B" instead of "8"

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [KiCad/kicad-website#318]
https://github.com/KiCad/kicad-website/blob/master/content/klc/F2.2.adoc

You say to use a `B`, then you use an `8`. 

Shouldn't this: `SOIC-8_3.2x5.7mm_P1.27mm` be changed to this: `SOIC-B_3.2x5.7mm_P1.27mm`?

ie: change `8` to `B`.

**Comment by marekr** [comment]
That adoc page includes tables. The table defines what prefix B means ;)

**Comment by ElectricRCAircraftGuy** [comment]
The table also shows zero examples using prefix B. So...let me get this straight: you're admitting the documentation page is wrong, ignoring it, and then closing the issue as resolved without fixing the typo?

**Comment by poeschlr** [comment]
The B would not be instead of the 8!

If the B is included the SOIC footprint would be named `SOIC-8_B3.2x5.7mm_P1.27mm`

**Comment by marekr** [comment]
@ElectricRCAircraftGuy 

https://i.imgur.com/RyfI1f7.png

**Comment by marekr** [comment]
@poeschlr if anything we have to rename "prefix" in the docs to "parameter" or something

**Comment by poeschlr** [comment]
Not sure if parameter is the right word here. I would say the parameters are the values that follow the letters we call prefix. (Maybe parameter identifier?)
