### ISSUE TITLE
KLC: Correct F9.1 screenshot

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-website#337]
The F9.1 screenshot is out of date with KiCad 5.0.0 (on Windows 10):

Current KLC screenshot:
![image](https://user-images.githubusercontent.com/7242621/45601886-5af35500-b9d1-11e8-9467-c2292004262c.png)

My screenshot:
![image](https://user-images.githubusercontent.com/7242621/45601898-95f58880-b9d1-11e8-8837-7e42854890e2.png)

I would replace this myself, but I'm unsure if it's required that the screenshots be taken on the same platform (e.g. Ubuntu).

**Comment by poeschlr** [comment]
Could you point out the differences (other than graphical style as this depends on the window manager)

So what text passages are different?

**Comment by DanSGiesbrecht** [comment]
- Ordering of fields
  - In the KLC screenshot, Reference and value appear after Doc and Keywords
- Name of fields
  - Doc/Document link

If this is inconsequential (and shouldn't be reported as an issue), I'll close this.

**Comment by marekr** [comment]
@poeschlr do you care if the pics aren't

**Comment by marekr** [comment]
Woops, don't mind me with that close/open.

@poeschlr Do you want pics to be all in the same OS/window style?

**Comment by poeschlr** [comment]
To be honest we might want to wait till the v5.1 feature freeze which should be quite near (If the plan to get 5.1 till fosdem should be reached)
I don't really care about OS and window style. We already have quite a mixture in the KLC. I doubt this will be a problem for understanding the KLC it self.

**Comment by diegoherranz** [comment]
I've just noticed this one while reviewing a footprint. Both the screenshot and the text needs updating.

**Comment by diegoherranz** [comment]
I think this can be closed after having merged #415

**Comment by nickoe** [comment]
Closed as of:

> https://github.com/KiCad/kicad-website/issues/337#issuecomment-507062918
