### ISSUE TITLE
KLC: Multiple file formats permitted - F9.3.6

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-website#338]
Bullet point 6 lists: required file format as **only** `.wrl`. Should this be `.wrl` and `.step`, referencing section M2.1?

Should there be a note for compatiblity with KiCad v4 here as well as in M2.1? Or is it assumed that KLC is intended for KiCad 5.0.0 onwards?

**Comment by poeschlr** [comment]
the footprint should always have wrl in the 3d settings. The file ending will be replaced automatically with step when needed. (A better solution would have been to get rid of the file extension completely but beggars can't be choosers)

**Comment by DanSGiesbrecht** [comment]
Thanks, @poeschlr ! This solved a question I had for a footprint PR as well.
