### ISSUE TITLE
KLC: S5.2 screenshot conflicts with S2.3

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-website#343]
The screenshot in S5.2 (below) shows multiple footprint filters for different packages:
![filters](https://user-images.githubusercontent.com/7242621/46913516-9be87600-cf4b-11e8-97b5-8b8c972c4b50.png)

However, [S2.3](http://kicad-pcb.org/libraries/klc/S2.3/) states that:
>Where atomic parts are available in multiple footprint options, a separate symbol must be drawn for each footprint.

I interpret that there should only be one footprint filter per symbol. Is that correct? Should the KLC be updated to reflect this? Specifically, should the screenshot in [S5.2](http://kicad-pcb.org/libraries/klc/S5.2/) be changed?

**Comment by poeschlr** [comment]
Only one footprint filter per symbol for fully specified symbols. Generic symbols can have multiple footprint filters if the designer wishes to reduce the number of allowed footprints.
Such a symbol will not have a default footprint set. (examples are the logic devices right now. And connectors in the past when we where unable to filter by library.)

**Comment by DanSGiesbrecht** [comment]
@poeschlr thanks! That resolves this, I think.
