### ISSUE TITLE
Redirection from https://kicad.org is broken again

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-website#348]
This looks to be the similar issue as #261.

@bombledmonk It looks like the https variant of kicad.org does not redirect properly. We have not yet got https for kicad-pcb.org.

**Comment by bombledmonk** [comment]
Hmmm... I'll report it.

**Comment by nickoe** [comment]
@bombledmonk hmm, from my end it does not look like it is fixed.

I get similar results on 
http://www.redirect-checker.org/index.php

I mean http is good, but https will just do a GET and get no response.

**Comment by bombledmonk** [comment]
alright, I'll push it back at them.

**Comment by bombledmonk** [comment]
Looks like there's some issues with downgrading and redirecting https to http for the time being.  I'll see if there's some other angle to work.

**Comment by nickoe** [comment]
Ok, thank you for following up on this. I will close this for now. I know that it could be problematic if at all possible.
