### ISSUE TITLE
No privacy policy

### ISSUE THREAD

**Issue by DXGLdotinfo** [KiCad/kicad-website#350]
The website has a Google Analytics tracker, but there is no privacy policy, so it is in breach of section 7 of the Google Analytics TOS (which requires disclosure of this tracker).

**Comment by marekr** [comment]
>You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies that are used to collect data. 

Well, that's the joke. We configure Google Analytics into "non-cookie" mode and feed it a false user fingerprint.

**Comment by DXGLdotinfo** [comment]
I do believe it is still required according to the Google Analytics TOS, which specifically says in section 7 it must be disclosed.

And I didn't even mention what Google Chrome says in the address bar now (and turns red when you enter text).

**Comment by marekr** [comment]
Fixed in 7069917
