### ISSUE TITLE
Error when create Pad

### ISSUE THREAD

**Issue by huyhtc** [KiCad/kicad-website#353]
1. I create a new footprint.
2. Place a  circular SMD Pad, pad number is 1.
3. add graphic line from the Pad.
4. Create Pad from selected Shapes on the line.

The error occurred.

![kicad error](https://user-images.githubusercontent.com/7598889/48596911-fc793180-e995-11e8-922d-7af200f0b2db.PNG)

![anchor pad](https://user-images.githubusercontent.com/7598889/48597034-9fca4680-e996-11e8-99d5-92e92d42cbd6.png)

Version: (5.0.1)-3, release build， Windows 10 64bit.

**Comment by antoniovazquezblanco** [comment]
Sorry @huyhtc but this is not the place to report a bug or malfunction in KiCad. This is the place to track errors related to KiCad webpage.

You should ask at the forums or, if you are sure that you are using the tool correctly, then post a bug report at https://bugs.launchpad.net/kicad
