### ISSUE TITLE
help file not helpful when creating  new component

### ISSUE THREAD

**Issue by atzed** [KiCad/kicad-website#365]
The helpfile for creating a new component is unclear. The used symbol for storing the new component does not exist (green Arrow down in opamp)
See getting started with kicad page 37/46 point 9 to 14. It just doesn't work.
The --  Preferences -> Component Libraries -- link does not exist either.
When I click -- Create New Symbol --- I have to choose an existing library where I was ment to make a new one. 
Needles to say I am confused.
Regards Atze.

**Comment by nickoe** [comment]
Please report this on the kicad-doc repo instead.
