### ISSUE TITLE
URLs are absolute, domain has no www

### ISSUE THREAD

**Issue by Caerbannog** [KiCad/kicad-website#37]
This does not cause any problem as far as I can tell, but most links use absolute URLs, for instance here is the generated HTML for a menu link:
```
<a href="http://kicad-pcb.org/post/">
```

Most cases could be replaced by the following, which seem more conventional to me:
```
<a href="/post/">
```

Benefits:
- Shorter text
- Serving HTTPS and HTTP simultaneously will be easier
- Does not depend on a specific hostname
Is there a reason not to change this? I would be happy to do the work.

Another subject is the canonical domain name, which used to be `www.kicad-pcb.org`, but has dropped the `www.` today. Is this intentional, and should we adapt the documentation?

**Comment by nickoe** [comment]
I guess it might be wiser to make the URL's relative.

About the cname, I don't think there is an explicit need to rewrite every reference to the version with www or without, both are supposed to always work.

I have not investigated what exactly needs to be adjusted to support the relative URL's properly. I guess it will just be a few places in the templating.
