### ISSUE TITLE
RSS looks broken

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-website#374]
http://kicad-pcb.org/index.xml

* Invalid publish date: ```<pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>```
* lots of items which do not belong to the blog, like every KLC rule

**Comment by nickoe** [comment]
This is how it has always been. It should probably only generate an entry for the blog thing. I am not exactly sure how this is controlled in hugo.

**Comment by marekr** [comment]
It's because we only set a "date" on the blog posts and not normal pages.
I rather just make hugo ignore non-blog pages. Fixing it just requires copying the base hugo template for rss and changing {{ range .Pages }} to be filtered to the blogs section.
