### ISSUE TITLE
when fill a pcb with adhesive layer

### ISSUE THREAD

**Issue by THARTARUS** [KiCad/kicad-website#375]
I can't fill my board perfectly with an adhesive layer because the poligon doesn't follow the rule as copper layer.
I would like to see that work like copper layer.
This need is necessary for flex-pcb or normal pcb with adhesive layer produce by a company as PCBWAY.

I'm sorry for my english.

![problem](https://user-images.githubusercontent.com/43825771/51620752-59174080-1f33-11e9-9c53-cab400ea4386.PNG)

**Comment by marekr** [comment]
Hi.

This repo is just for the kicad website.

Any requests, bugs and feedback for KiCad should go here https://bugs.launchpad.net/kicad
