### ISSUE TITLE
Website not connecting - "This site can't be reached"

### ISSUE THREAD

**Issue by DanSGiesbrecht** [KiCad/kicad-website#379]
Not sure if this is the correct place to report this - the website appears to be down, as of 8:52a.m. (MT).

On Google Chrome:
![chrome-error](https://user-images.githubusercontent.com/7242621/52285868-61548000-2924-11e9-929d-ebfdb037b3fa.png)

**Comment by nickoe** [comment]
This is known, use www.kicad-pcb.org in the meantime. I will close this issue as this is configured outside the website source.

**Comment by DanSGiesbrecht** [comment]
Where should this normally be reported?

**Comment by herostrat** [comment]
@nickoe because I do not know a better way (yet) for this, and although I am sure you already noticed this:

The SSL certificate is not accepted.
I use HTTPS everywhere, so the "normal" user would probably not notice as the HTTP version works as expected, but I wanted to let you know nontheless

**Comment by nickoe** [comment]
@herostrat yeah, I know. But Rome was not built in a day, it was build during the night, and this is the time I sleep. In other words, things take time.

**Comment by nickoe** [comment]
I have disabled the secure route to the pod to confuse you more.

**Comment by herostrat** [comment]
I know, it was no critique just an information if it slipped through some checks.
But if it is not wanted to report errors/bugs in this regard it is ok for me.

Why would that confuse me?
I know that the hosting was moved to the cern and therefore the certificate will also get moved.

Just thought it is interesting for you as you configure this stuff, at least that's what I gathered in the mailing list.
But I guess I was wrong, so please feel free to ignore my comments
