### ISSUE TITLE
KLC: F5.1: Fix Silkscreen clearance

### ISSUE THREAD

**Issue by myfreescalewebpage** [KiCad/kicad-website#392]
Silkscreen clearance has been pointed by @evanshultz in https://github.com/KiCad/kicad-footprints/pull/1050#issuecomment-434022340 to be actually 0.2mm in the KLC but that the IPC-7351C recommended distance, 0.12mm, is allowed:

> http://kicad-pcb.org/libraries/klc/ are the official library rules and http://kicad-pcb.org/libraries/klc/F5.1/, clause 2, specifically says 0.2mm. However, this hasn't been updated and we've been allowing IPC 7351C draft recommendation of the line width (so just 0.12mm). Either one is an acceptable silk-pad clearance.

I have personally accepted several footprints with 0.12mm silkscreen clearance and many other are designed like that I suggest KLC should be updated.

Please let me known, I can submit a PR if other @KiCad/librarians agree.

Cheers,
Joel

**Comment by poeschlr** [comment]
I would suggest a wording similar to:
- Clearance between silkscreen and exposed copper elements is suggested to be 0.2mm where feasible. It must be at least the same as the silk line with (0.12mm) or more than the pad mask expansion (whichever is greater).

**Comment by diegoherranz** [comment]
>It must be at least the same as the silk line with (0.12mm)

Does the fact that "the silk line width" is referenced mean that the clearance can be 0.10mm if that line width is used on a high density design? Honest question.

Also please note typo on `width`.

Thanks.

**Comment by evanshultz** [comment]
Hopefully this is all taken into account at https://github.com/KiCad/kicad-website/pull/417. I just noticed this so I didn't copy the suggested that's above, but I believe I captured the intent.

**Comment by myfreescalewebpage** [comment]
I think #417 is great.
Closing this issue now.
