### ISSUE TITLE
Spelling Error KLC S5.2

### ISSUE THREAD

**Issue by b1ackmai1er** [KiCad/kicad-website#394]
http://kicad-pcb.org/libraries/klc/S5.2/

Neighter the size of the exposed pad nor the size of the mask cutout are included.

Should be "Neither"

# KiCad **WEBSITE** issue guidance.

Thanks for opening an issue. We accept both suggestions and bugs :D

This issue tracker is **ONLY** used for issues/suggestions with the KiCad **WEBSITE** including the KLC.

KiCad application related issues should go here: [launchpad](https://bugs.launchpad.net/kicad)
KiCad documentation content related issues should go here: [kicad-doc](https://github.com/KiCad/kicad-doc)
KiCad documentation website related issues should go here: [kicad-doc-website](https://github.com/KiCad/kicad-doc-website)

**Comment by nickoe** [comment]
Please fix the issue description.
