### ISSUE TITLE
About the mirroring problem of adding a new China region

### ISSUE THREAD

**Issue by taotieren** [KiCad/kicad-website#395]
Hello, I submitted a request for a new image to TUNA [https://github.com/tuna/issues/issues/526#issuecomment-475134252] and DGLUG [https://github.com/dglinux/issues/issues/9], and now I have encountered the problem of using a synchronous method to create a mirror. So solve the problem of downloading kicad in China.

**Comment by taotieren** [comment]
The mirror synchronization method is best to achieve incremental synchronization.

**Comment by taotieren** [comment]
Mainly to solve the problem that Chinese regional users can't download or download slowly. Many regions in China are unable to access GitHub or access GitHub very slowly, including some excellent open source websites, so some open source organizations in mainland China began to provide some mirrors download services.

**Comment by marekr** [comment]
That's why GitHub isn't the primary option and instead CERN is. The CERN
download also isn't real AWS. But you should be able to access it via the
same tools. Just be sure to disable sign requests. The endpoint URL is
s3.cern.ch and the bucket is kicad-downloads.

While you can freely mirror KiCad. We cannot link to Chinese mirror sites
without an existing dev member being in control to preventing tampering of
packages.

**Comment by taotieren** [comment]
Will I add a GPG signature in the future? Similar to Archlinux's AUR package signature management.

**Comment by taotieren** [comment]
In China, visit the CERN website to download the night version of KiCad. The download speed is only about 50KB/s. After about 5 hours of downloading, there may be problems such as losing packets and losing connections.

**Comment by taotieren** [comment]
I submitted a request to add kicad-git version to ArchlinuxCN[https://github.com/archlinuxcn/repo/issues/1078], which has been included in ArchlinuxCN, and the download speed has been increased from 30KB/s to 5MB/s.

**Comment by z4yx** [comment]
TUNA mirror is now available at https://mirror.tuna.tsinghua.edu.cn/kicad/

**Comment by marekr** [comment]
I'm not deaf to the chinese firewall problem killing download speeds.

But we need a way to validate that packages are always the _correct_ and _exact ones_. Us controlling mirrors directly is the only immediately easy way to do that. Not that it's foolproof but it has a higher level of assurance.

PGP signatures and hashes don't work by themselves. The majority of Windows users will not use them which means we'll have to write an automated bot to constantly download files and verify signatures of uncontrolled mirrors which requires resources to do.

**Comment by pointhi** [comment]
using torrents could solve this issue (do not know how torrents are handled inside china)

**Comment by marekr** [comment]
@pointhi They still need domestic seeders. Torrents don't magically just work.

**Comment by marekr** [comment]
@stambaughw What do you think here? The best I would be willing to do is put it on the downloads page with massive THIRD PARTY, USE AT YOUR OWN DISCRETION warning in giant font. lol

**Comment by stambaughw** [comment]
@marekr I concur, the KiCad project is not responsible for third party downloads outside of our control and should only be used at the user's own discretion with all of the usual caveats.  That's the only way I would consider doing this.  AFAIK, there isn't a big enough font for that warning. ;)

**Comment by sethhillbrand** [comment]
Can I open this question again?

We don't control how kicad is packaged on most distributions.  I'm not sure I see the distinction between listing an unverified mirror and listing, for example. the Sabayon or openSUSE distributions.  

We should place this under a "3d-party, unverified" sub-header but after that, providing local mirrors is a good way to improve our userbase in the Pacific region

**Comment by marekr** [comment]
But Linux distro repos are inherently a high trust source, you are afterall, getting all your system packages from it. The only exception we have is the PPA but it has earned it's trust after all these years.
I'm not against a 3rd party list but it has to be clearly marked, even the name of the source must be spelled out, not just 'TUNA'

**Comment by sethhillbrand** [comment]
OK, I can help with that.  @taotieren Can you provide the full name of the locations providing mirroring services?

**Comment by z4yx** [comment]
Hi, I'm one of the administrators of the mirror site. TUNA is short for the Tsinghua University student Network Association.  
The official name of mirrors.tuna.tsinghua.edu.cn is Tsinghua Open Source Mirror, which is maintained by TUNA, and supported by Tsinghua University.

**Comment by taotieren** [comment]
@sethhillbrand Thanks!

**Comment by taotieren** [comment]
> using torrents could solve this issue (do not know how torrents are handled inside china)

In China, torrents is controlled, using open source torrents tools to download almost no download speed. 
Only a few audited tools from the Windows platform can be used to download torrents.

**Comment by weearc** [comment]
Hi I'm the administrator of Chongqing University Open Source Software Mirror. And we've also mirrored Kicad to speed up downloading progress. ( https://mirrors.cqu.edu.cn/kicad/ ) This mirror is maintained by Lanunion and supported by Networking and Information office of Chongqing University .

**Comment by marekr** [comment]
Added in 872c737ec9245efa30ed3cc3d09fe006409fe2dd

**Comment by billchenchina** [comment]
Hi~ also a mirror site from Harbin  Institute of Technology
http://mirrors.hit.edu.cn/kicad/

**Comment by marekr** [comment]
I can't even visit that one, just times out.

**Comment by billchenchina** [comment]
> I can't even visit that one, just times out.

Ahh... sorry for that. Our mirror site is now IPv6-only so perhaps you can't visit it.

**Comment by sethhillbrand** [comment]
At a minimum, we do need to verify that we can see and download the KiCad files.  I have an IPv6 connection and can't get to the site.  

```
seth@shop % wget -6 mirrors.hit.edu.cn                                                                                                                 ~
--2019-11-25 19:25:58--  http://mirrors.hit.edu.cn/
Resolving mirrors.hit.edu.cn (mirrors.hit.edu.cn)... 2001:da8:b800:253::aa0:41f
Connecting to mirrors.hit.edu.cn (mirrors.hit.edu.cn)|2001:da8:b800:253::aa0:41f|:80... failed: Network is unreachable.
```

**Comment by taotieren** [comment]
I used Manjaro Linux to install kicad-git download speed through AUR, and I applied for a request to package KiCad-git on ArchlinuxCN, which has been merged into the warehouse. 
It can solve the problem of slow download of AUR. 
The AUR package on ArchLinuxCN uses GPG signature verification.

https://github.com/archlinuxcn/repo/issues/1078

**Comment by genelocated** [comment]
@sethhillbrand The full name of mirrors.dgut.edu.cn is _Dongguan University of Technology Open-source Software Mirror_. It is maintained by DGUT GNU/Linux Association, backed by Dongguan University of Technology and located in Dongguan, Guangdong.

**Comment by billchenchina** [comment]
> At a minimum, we do need to verify that we can see and download the KiCad files. I have an IPv6 connection and can't get to the site.
> 
> ```
> seth@shop % wget -6 mirrors.hit.edu.cn                                                                                                                 ~
> --2019-11-25 19:25:58--  http://mirrors.hit.edu.cn/
> Resolving mirrors.hit.edu.cn (mirrors.hit.edu.cn)... 2001:da8:b800:253::aa0:41f
> Connecting to mirrors.hit.edu.cn (mirrors.hit.edu.cn)|2001:da8:b800:253::aa0:41f|:80... failed: Network is unreachable.
> ```

Well, it seems everything is working well from my computer.
```
$ wget -6 mirrors.hit.edu.cn
--2019-11-26 11:56:35--  http://mirrors.hit.edu.cn/
Resolving mirrors.hit.edu.cn... 2001:da8:b800:253::aa0:41f
Connecting to mirrors.hit.edu.cn|2001:da8:b800:253::aa0:41f|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 575 [text/html]
Saving to: ‘index.html’

index.html           100%[====================>]     575  --.-KB/s    in 0s

2019-11-26 11:56:35 (20.7 MB/s) - ‘index.html’ saved [575/575]
```
Check your connection may help

**Comment by sethhillbrand** [comment]
@billchenchina I have tried from multiple servers in New York, Chicago and San Francisco.  None can reach the server.  It may be restricted to China only.

**Comment by marekr** [comment]
I really do not want to include because htmlproofer that validates all website links will just vomit on it.

**Comment by taotieren** [comment]
@billchenchina Can the mirror station of Harbin Institute of Technology be accessed through the public network? 
I was unable to access it in Guangzhou.

**Comment by weearc** [comment]
Also cannot visit from chongqing at the same time, be it telecommunication exportation or education net exportation.



 
---Original---

**Comment by marekr** [comment]
I added Dongguan University as it works and that'll be it for now....I don't think we need every single possible university's mirror
