### ISSUE TITLE
Need a custom 404

### ISSUE THREAD

**Issue by Caerbannog** [KiCad/kicad-website#40]
We definitely need a custom 404 page with a single click to the homepage.
This requires some server configuration to use 404.html, which is currently empty.

This is especially important since most inbound links are now broken... Just try googling for KiCad.

**Comment by marekr** [comment]
http://gohugo.io/templates/404/

Server needs to be changed to point to the 404.html

**Comment by Caerbannog** [comment]
This now works, see: http://kicad-pcb.org/abc

**Comment by nickoe** [comment]
Yes, we have now enabled it, so we can close this issue.
