### ISSUE TITLE
BPW21 symbol connected to wrong pins of the package

### ISSUE THREAD

**Issue by IMMRMKW** [KiCad/kicad-website#402]
I used the BPW21 from the 'sensor optical' library in a design for a PCB to convert its current to a voltage using an opamp. I couldn't get the circuit to work on my PCB. Turns out that the symbol of the photodiode and the corresponding package have the pins mixed up. Look at the datasheets:

http://www.farnell.com/datasheets/2711550.pdf?_ga=2.161216436.869783962.1555001329-1543896970.1496776002&_gac=1.216587876.1553760570.Cj0KCQjw4fHkBRDcARIsACV58_FCy4D8MmG6kpos4OOzktEW5Qzu4ywSayQft_koIFx3qKCRAmxGZZgaAs2mEALw_wcB
and
http://www.farnell.com/datasheets/2047599.pdf?_ga=2.173348010.869783962.1555001329-1543896970.1496776002&_gac=1.155123274.1553760570.Cj0KCQjw4fHkBRDcARIsACV58_FCy4D8MmG6kpos4OOzktEW5Qzu4ywSayQft_koIFx3qKCRAmxGZZgaAs2mEALw_wcB

Please correct me if I am wrong.

**Comment by marekr** [comment]
This repo is only for the kicad website. You must find the corresponding repo for the symbol you are having trouble with instead.

https://github.com/KiCad/kicad-symbols
