### ISSUE TITLE
How to unselect a highlighted net?

### ISSUE THREAD

**Issue by E3V3A** [KiCad/kicad-website#403]
I suppose there is something lacking in the documentation, because once I hit the **`highlight net`** button, the net remains highlighted no matter what I do. How do you undo this operation?

**Comment by marekr** [comment]
> KiCad WEBSITE issue guidance.
> 
> Thanks for opening an issue. We accept both suggestions and bugs :D
> 
> This issue tracker is **ONLY** used for issues/suggestions with the KiCad WEBSITE including the KLC.
> 
> KiCad application related issues should go here: [launchpad](https://bugs.launchpad.net/kicad)
>**KiCad documentation content related issues should go here: [kicad-doc](https://github.com/KiCad/kicad-doc)**
> KiCad documentation website related issues should go here: [kicad-doc-website](https://github.com/KiCad/kicad-doc-website)

**Comment by E3V3A** [comment]
Either way, I resolved the problem by restarting KiCad. Somehow the highlight got locked and wouldn't change. Thanks and sorry for posting in the wrong place.

**Comment by marekr** [comment]
No worries.

You can always ask http://forum.kicad.info here for help.
