### ISSUE TITLE
Page recommended in ReadMe but not found

### ISSUE THREAD

**Issue by LiquiphonicsHiFi** [KiCad/kicad-website#412]
I am fairly new to Kicad and totally new to Github so hope this post is as it should be.
I am installing Kicad V5 (I think it is version 5 but cannot find anywhere that tells me including the Mac's 'Info' panel).  The ReadMe file says . . .

"* In general, please see http://kicad-pcb.org/help/migration/ when upgrading KiCad to new major version (i.e. V4 to V5)."

. . . but when I load that page, I am told that page does not exist and that I should report to GitHub - which is this post now.

Hope this is helpful,

Matt

**Comment by nickoe** [comment]
I think that page was renamed to http://kicad-pcb.org/help/upgrading/

**Comment by nickoe** [comment]
@marekr  It is a bit strange that the alias does not seem to work.

https://github.com/KiCad/kicad-website/commit/b77a41722831c3ba522eacb1dbf3a758cdcc4e89#diff-7d72dcd5af7276087ce49869e184728f

**Comment by LiquiphonicsHiFi** [comment]
> @marekr It is a bit strange that the alias does not seem to work.
> 
> [b77a417#diff-7d72dcd5af7276087ce49869e184728f](https://github.com/KiCad/kicad-website/commit/b77a41722831c3ba522eacb1dbf3a758cdcc4e89#diff-7d72dcd5af7276087ce49869e184728f)

Ah, yes, that one seems to work.  Thanks nickoe.
