### ISSUE TITLE
Admonition blocks have different layout depending on being content page or blog post

### ISSUE THREAD

**Issue by nickoe** [KiCad/kicad-website#414]
It looks like the admonition blocks have different layout depending on being content page or blog post.

I just added it for the windows.adoc and it renders a broken image for the "admonition" image.

But on the blog on the bottom of http://kicad-pcb.org/blog/2016/04/In-Development-3D-Plugins/, we see that it just says "Note" and don't have a broken image link.

**Comment by marekr** [comment]
Meh, its the :icons: statement that needs to be manually added per adoc file

7e7c9170e6edd0f99e5a03772e482e8c5d892343
