### ISSUE TITLE
Can't open Linux Schematic with Windows

### ISSUE THREAD

**Issue by bekoger** [KiCad/kicad-website#420]
If I create a KiCad Schematic with Xubuntu and open this Schematic with Windows, 
I get an Error on read the Symbol-ID.
The problem seems that the Symbol-ID at Linux is 16 Bytes long, 
but at Windows the Symbol-ID is only 8 Bytes long.

Xubuntu System
Application: kicad
Version: 5.0.2-bee76a0~70~ubuntu18.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Platform: Linux 4.15.0-43-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 2.24
    Boost: 1.65.1
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.58.0
    Compiler: GCC 7.3.0 with C++ ABI 1011

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=OFF
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_WXPYTHON=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

Cut from schematic-File generated with LINUX (ID from U 1 is 16 Bytes long)
$Comp
L SuplySwitchTest-V1-eagle-import:LTC4359 IC1
U 1 0 7C8C299E06F92037
P 6300 3600
F 0 "IC1" H 6000 3600 34  0000 L BNN
F 1 "LTC4359" H 6300 3600 34  0000 L BNN
F 2 "SuplySwitchTest-V1:MS8" H 6300 3600 50  0001 C CNN
F 3 "" H 6300 3600 50  0001 C CNN
	1    6300 3600
	1    0    0    -1  
$EndComp

Windows System
Application: kicad
Version: (5.0.2)-1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.61.1 OpenSSL/1.1.1 (WinSSL) zlib/1.2.11 brotli/1.0.6 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.34.0
Platform: Windows 8 (build 9200), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8)
    Boost: 1.68.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.61.1
    Compiler: GCC 7.3.0 with C++ ABI 1011

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=OFF
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

Cut from schematic-File generated with Windows (ID from U 1 is 8 Bytes long)
$Comp
L Face2FaceMikroPTT_Haka_Left-eagle-import:1,6_0,8 P?
U 1 0 2701E361
P 2600 5300
F 0 "P?" H 2555 5373 59  0000 L BNN
F 1 "Earph+" H 2555 5170 59  0000 L BNN
F 2 "Face2FaceMikroPTT_Haka_Left:1,6_0,8" H 2600 5300 50  0001 C CNN
F 3 "" H 2600 5300 50  0001 C CNN
	1    2600 5300
	1    0    0    -1  
$EndComp

**Comment by nickoe** [comment]
reported at https://bugs.launchpad.net/bugs/1838365
