### ISSUE TITLE
Garbled Japanese characters with "Place text" in KiCad 5.1.2-2

### ISSUE THREAD

**Issue by G00Keish** [KiCad/kicad-website#426]
When I input Japanese with "Place text" function, garbled characters occur.

However, check the properties, It is displayed without being garbled.
This seems to have occurred because the CAD font does not support Japanese.

・Windows 10 Pro ver 1903 Japanese environment
・KiCad ver 5.1.2-2

![mojibake](https://user-images.githubusercontent.com/54165740/63146175-07501800-c035-11e9-84b6-87fa57a26161.png)

Thank you.

**Comment by poeschlr** [comment]
This is not the place to report KiCad bugs. See: http://kicad-pcb.org/help/report-a-bug/

---

Additionally: 5.1.4 has been released you might consider updating.

**Comment by G00Keish** [comment]
Sorry! I missed it.
Thank you for the information and your kindness.
