### ISSUE TITLE
KLC G1.1 only refers to names

### ISSUE THREAD

**Issue by chschlue** [KiCad/kicad-website#431]
KLC G1.1 only mentions names while there also is an unwritten rule to also restrict other fields (especially descriptions) to just A-Za-z0-9_-.,+
Discussions https://github.com/KiCad/kicad-symbols/pull/2090#issuecomment-528916946 and https://lists.launchpad.net/kicad-developers/msg42059.html

G1.1 should either be expanded to include more than names or, preferably, relaxed to include more characters. The answers on kicad-developers are inconclusive as of now, but apparently at least all printable 7-bit ASCII characters should be ok for everything that cannot reasonably be expected to end up as a filename.

**Comment by chschlue** [comment]
What I found so far:
* Current character set was introduced in 3a5a153b82f8b69c9d03b29b075fdaf5b213c80f, apparently out of thin air
* https://lists.launchpad.net/kicad-developers/msg42060.html says \\/:"<>| are forbidden in filenames. Don't know why that list is so short (e.g. * and ? are outright illegal on Windows and can lead to ugly escaping bugs on other systems)
* There are 26 UTF-8 encoded "µ"s in kicad-symbols master right now which apparently don't cause any problems

**Comment by poeschlr** [comment]
Symbol libs are not one file per symbol right now so they do not fall under this restriction right now. (At least not for this reason.) However it is still not clear if v6 will be one file per symbol or one file per library so we should not yet relax the rules here.

I remember that there actually was a discussion about which characters to allow and we came to use the set documented because of that.
I am not prepared to extend this rule at this point in time. We know the current ruleset is save so why risk breaking stuff without good reason?

I also do not feel the rule should extend to more than names. If other parts of assets need restricting then we can introduce separate rules for them. (I am however not aware of restrictions for anything other than names)
There is however an implicit rule: The library uses english (which gets rid of most problem areas all on its own as english has a very limited character set.)

**Comment by poeschlr** [comment]
By the way the original restriction comes from before the KLC was on the website: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

**Comment by chschlue** [comment]
Maybe I should word this differently, I think your answer completely misses the point.
I'm fine with restricting symbol names or everything else that may turn into a file name in future versions.

My objection is that G1.1 cannot reasonably be interpreted to restrict symbol _descriptions_ while current practice is to do just that for new symbols, so either the rule or the practice should be changed.

I'm leaning towards being more permissive when it comes to descriptions. I'm not talking about allowing runes or hieroglyphs, but technical fields tend to make use of Greek letters and other symbols, even in English (and crutches like replacing µ with u are an anachronism IMHO)
This should at least be open for discussion (and coordination with devs, but the thread @evanshultz started on kicad-developers seems to be dead)

**Comment by poeschlr** [comment]
I am not aware of the fact that we restrict the character set for description fields. (other than to englisch language obviously) Also remember the description field and keyword field are never shown in the schematic so my comment regarding "can kicad render it" does not apply here either.

So this leaves the value and reference fields which both are restricted by other rules (value filed by the fact that it is equal to the symbol or footprint name, The reference field by the KLC rule set out for it.)
The datasheet field is of course restricted to being a valid url (there is as of yet not a rule requiring this.)

The only thing left are pin names. I am not really sure what the exact rules are for these (i did not find them in the KLC) but my guess is something like:
- Pin names are based on the names used in the datasheet
- Pin names are capitalized (use no lower case letters)
- Pin names are kept short but must still allow for unique identification of pins
  - For pins with multiple alternative functions only the main identifier plus most common function is included

**Comment by chschlue** [comment]
https://github.com/KiCad/kicad-symbols/pull/2090#issuecomment-528942770
https://github.com/KiCad/kicad-symbols/pull/1885#issuecomment-496800606 (I know this was a mistake in the first place, still the request is to "remove special characters")
https://github.com/KiCad/kicad-symbols/pull/2005#issuecomment-515099176
https://github.com/KiCad/kicad-symbols/pull/1947#issuecomment-507718483

This was far from an exhaustive search but I hope it helps establish that I'm not hallucinating.
Note that G1.1 is mentioned several times although it doesn't apply (as you confirmed yourself.)

**Comment by poeschlr** [comment]
regarding 1885 it might just have been worded wrong (the strange o made no sense there)
2090 was a misunderstanding (i worded my comment poorly)

---

The other two are misinterpretation of g1.1, I personally feel these requests might have been made wrongly. But i leave this for evan to decide. (If he wants the description field to be restricted then there should be a rule for it in the KLC. I am however not aware of a technical reason as to why we should do it.)

**Comment by chschlue** [comment]
> If he wants the description field to be restricted then there should be a rule for it in the KLC. I am however not aware of a technical reason as to why we should do it.

Exactly what I'm saying and trying to get comments on.
kicad-website may not be the best place anymore.

**Comment by poeschlr** [comment]
the website is the place where we generally discuss klc stuff so yes it is the right place

**Comment by evanshultz** [comment]
I'm sure I did something wrong. That shouldn't be under discussion. :)

I don't recall previous discussion of this part of KLC. Maybe Oliver remembers something, if we care to dig into the history.

However, while we break or bend KLC frequently, I've asked the contributors to adhere to the character set from G1.1 in the two PRs above but it was not in my mind that this clause doesn't specifically mention descriptions and keywords. That is my fault. You can see I commented that the square root looked fine to me.

I'm quite in favor of opening up G1.1 based on what we know now, but I would like to determine the allowable characters and then update KLC first so we have a guideline at which to direct contributors. If descriptions and keywords have a wider set of characters than file names and library names, that's great with me. As long as we mention that we are all on the same page in the future. Sound good? I'm happy to submit a PR to update this clause of KLC if y'all would like.

**Comment by chschlue** [comment]
I'm not trying to blame anyone for anything, I'm trying to find out if and why such a restriction might be necessary.
I don't think this is urgent, so it's probably better to wait if something substantial turns up on kicad-developers.

**Comment by evanshultz** [comment]
So can G1.1 be re-worded to blacklist only the following characters in file names (symbol library names and footprint names): `\/:"<>|[]{}` plus space out of an abundance of caution? And thus all other characters are allowed (the reverse of the current clause which is a whitelist)?

Also, I would like to explicitly mention descriptions and keywords have no restrictions.

Lastly, should we add a clause to restrict 'character' to mean a single readable character, to avoid any attempted misuse of using escape characters or UTF characters or something? Or am I being paranoid?

**Comment by poeschlr** [comment]
All my IT security teaching says: Never ever use a blacklist of chars if you want something to be secure. To be honest i see no reason why we should expand the list of allowed chars for filenames. As i made clear this list is only for filenames so i see therefore no reason why we should expand this rule.

And no this rule stays for filenames alone. If you want to capture other fields then please make a new rule for them.

**Comment by chschlue** [comment]
Full ACK. I see no problem in leaving the allowed character list for (potential) filenames as is.

This topic has basically become "Codify allowed characters in symbol descriptions".

**Comment by poeschlr** [comment]
The datasheet (by maxim) uses the letter u instead of µ (So seems like this will not be a problem after all): https://pdfserv.maximintegrated.com/package_dwgs/21-0036.PDF

**Comment by chschlue** [comment]
Then the matter should be settled for now, at least as far as G1.1 is concerned.
