### ISSUE TITLE
SSL certificate on kicad-pcb.org isn't valid for the URL

### ISSUE THREAD

**Issue by tijuca** [KiCad/kicad-website#447]
If a user is open https://kicad-pcb.org/ he will get a big warning from the web browser.

> Errorcode: SSL_ERROR_BAD_CERT_DOMAIN

The root for this is clear, but it will give a bad user experience. It also makes it quite useless to build a redirection from http -> https.
Please adjust the used SSL certificate for https instance.

And further more please make the KiCad official website completely available by https.

**Comment by nickoe** [comment]
There is no redirection from http to https on kicad-pcb.org setup.

**Comment by tijuca** [comment]
And I haven't nowhere written that something like this is existing. ;) But kicad-pcb.org is one of the web sites that doesn't redirect traffic to https only.

**Comment by chschlue** [comment]
I second this.
CERN's certificate already has lots of SANs, adding kicad-pcb.org can't be that much trouble.

**Comment by nickoe** [comment]
@tijuca  I may have misunderstood what you mean by:

> It also makes it quite useless to build a redirection from http -> https.

**Comment by tijuca** [comment]
@nickoe 
Well, it simply means that the current certificate isn't usable for using some redirect mechanism. But for me a web site that mainly only serves content only by http isn't really up to date in nowadays.

So in the end there are two problems existing to server the web site of the KiCad EDA by https.

1. Update or create the existing certificate so it's also valid for kicad-pcb.org
2. Create a redirection within the site configuration so the user is automatically moved to get data by https

**Comment by chschlue** [comment]
Didn't notice kicad-pcb.org isn't actually served over HTTPS before.
Still, https://kicad-pcb.org/ presenting a certificate for a domain name that is completely unrelated at first glance is at least bad style.

**Comment by marekr** [comment]
>But for me a web site that mainly only serves content only by http isn't really up to date in nowadays.

Why? We have no forms to fill out, you give us no private content.

**Comment by tijuca** [comment]
Sorry, I don't want to discuss why https ist better than http if you seem to not accept that encrypted traffic is from a security perspective always better than non encrypted.
Downloads of Windows installer files e.g. are already provided on the web server by an link that points to a https resource, so why not for the whole web site?. So the time for http is over and there is really no need to keep on http in a midterm.

As you modified your answer multiple times, the Debian package files have included multiple hash sums which must fit the content within the Packages file. This file itself has a GPG signature from the FTP team. By this it's fairly non-trivial to inject on the user side manipulated packages. Windows and related installer files doesn't have such a system. But you are free to use also https for apt. It's just working.

**Comment by thawkins** [comment]
> > But for me a web site that mainly only serves content only by http isn't really up to date in nowadays.
> 
> Can you justify why? We have no forms to fill out, there is nothing private when browsing the kicad site.

Google has been "marking down" the relevance of sites that are not ssl,, so having HTTP only reduces your ranking on google search.

**Comment by Goury** [comment]
> Downloads of Windows installer files e.g. are already provided on the web server by an link that points to a https resource, so why not for the whole web site?

Probably for NSA to be able to MITM replace those links to ones with trojans?

Just stop resisting obvious and start treating your visitors with respect.    
People deserve privacy.    
HTTP is opposite of privacy.    
I don't want my every neigbour, my ISP and my government and also millions of other MITMs to even know what websites I visit.    
Nor do I want them to be able to hijack my traffic, serving me something they want instead of what was served by the web server.    
But if I go to kicad-pcb.org I have to tell everyone around and along the road that I'm going there and I have to take the risk of getting to the wrong place.    

All this because some stubborn server administrator doesn't want HTTPS.    
Have he tried what good this lack of HTTPS ever done to anyone besides saving a few CPU cycles?

**Comment by marekr** [comment]
>All this because some stubborn server administrator doesn't want HTTPS.

I'm not even the "server admin" nor have any power to change it  ;)
I would have just implemented it if I could since it's not a big deal.


>Probably for NSA to be able to MITM replace those links to ones with trojans?

They can just national security letter any default Certificate Authority to give them a fraudulent but legitimate SSL certificate if they actually cared ;)


>I don't want my every neigbour, my ISP and my government and also millions of other MITMs to even know what websites I visit.

Your problem is you want DoH, HTTPS does not fix this.

**Comment by nickoe** [comment]
Discussing this here is not helpful, as it is not managed here anyways.

**Comment by Goury** [comment]
@nickoe 
And closing security issue without ever resolving it does?

**Comment by tijuca** [comment]
I'd suggest we all take a deep breath and calm down. Heated discussions far away from technical arguments wont bring this topic further. The world isn't going down if the website kicad-pcb.org isn't provided by https (only).

Using shared and central organized structures aren't easy and flexible to handle with, and like me all involved parties are working on a volunteering base I guess. It's probably going like always in the FOSS world, it's done when it's done.

**Comment by Goury** [comment]
Actually, world is going down because of this.
Is there a problem to get a bit of donations and use it to rent a decent virtual server?

**Comment by tijuca** [comment]
**No it isn't!** Please stop thinking religious.

And no there is no problem with getting a dedicated web server, there is no need for. The CERN is providing webspace and infrastructure for free, but it's not the responsible for the content the KiCad project is using. As written previously by me, using such provided infrastructure means also you have to accept some rules. Using a mixed SSL CA is one of them. As we all have no deeper knowledge what's really needed behind the scenes I think it's better to shut up and being kindly to people who trying to do the work. Last comment to this topic from myself.

**Comment by marekr** [comment]
Rejoice. Both the main and docs website are now https enabled.

**Comment by sethhillbrand** [comment]
Way to go @nickoe!
