### ISSUE TITLE
Please add FreeBSD to the list of platforms where Kicad is available

### ISSUE THREAD

**Issue by yurivict** [KiCad/kicad-website#449]
http://www.kicad-pcb.org/download/

The FreeBSD port is available: https://www.freshports.org/cad/kicad

It can be installed with the 'pkg install kicad' command.

**Comment by marekr** [comment]
Added, BSD is always the odd one out, I don't think any upstream dev uses it at all.

**Comment by yurivict** [comment]
Thanks!

But why didn't you add a link to the "Downloads" page http://www.kicad-pcb.org/download/ like all for other systems?

One of these icons could be used there:
* https://p7.hiclipart.com/preview/834/814/485/computer-icons-freebsd-portable-network-graphics-clip-art-scalable-vector-graphics-freebsd-icon-thumbnail.jpg
* https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3fIveTeZGB7cAD1zV9D8QJQ1svZwwUYWzQQazYxOq74B8gJlM&s

**Comment by marekr** [comment]
@yurivict It's there now, the website is deployed automatically via CI but it takes a few hours to trigger.

**Comment by yurivict** [comment]
Thank you!
