### ISSUE TITLE
KiCad bug reporting moved to GitLab, but the website is not updated

### ISSUE THREAD

**Issue by cebrax** [KiCad/kicad-website#467]
I type "kicad bug" to Google.. I click on the first link which leds me to "Report a Bug | KiCad EDA". Link is https://www.kicad-pcb.org/help/report-a-bug/.

However, information there is not up to date..

**Comment by cebrax** [comment]
Edits are not sufficient.. Page still has link to launchpad and also mentions launchpad..

**Comment by marekr** [comment]
Thanks. The page will get a rewrite late.
