### ISSUE TITLE
Screen switching issue with Mac Retina and external screen

### ISSUE THREAD

**Issue by hb020** [KiCad/kicad-website#474]
**Environment:**
MacOS 10.15.3
Kicad 5.1.5-0-10_14
MBP Retina with external screen

**Symptoms:**
when moving any pcb or schema from one screen to another, the scaling is off: crosshair and mouse do not overlap, contents scroll badly, etc.

**Workaround:**
NOT the workaround that is noted in https://kicad-pcb.org/help/known-system-related-issues/#_high_dpi_screens 1, but:
option 1: go to non-accelerated mode (but then it becomes unusably slow on the internal screen)
option 2: close the window with the drawing, and open it again. The drawing will be alright now, but you’ll have the same issue when moving back to the other screen.

This is handled in https://gitlab.com/kicad/code/kicad/issues/2592

**my suggestion:**
Please update the above mentioned “known-system-related-issues” page, as what is mentioned on that page is NOT the solution for this case, or add these workarounds in the MacOs section of that page.

**Comment by cpresser** [comment]
This seems to be fixed in the upcoming 6.0 and it might get back-ported to 5.1.6:
https://gitlab.com/kicad/code/kicad/-/merge_requests/110

Anyway, feel free to propose a patch.

**Comment by nickoe** [comment]
@hb020 This should be merged for 5.1 as well. See https://gitlab.com/kicad/code/kicad/-/merge_requests/110#note_321923051

I don't think the nightly macos builds for 5.1 are running right now, but I consider it fixed just not properly released everywhere yet. You could try the normal nightlies from the master branch in the meantime.

**Comment by hb020** [comment]
Well, it indeed looks like this got backported into 5.1.6, but the issue is still there in 5.1.6.
Not a biggy, I can work around it. But still a heads up since maybe something got messed up with the merges?
