### ISSUE TITLE
Cursor offset after screen switching with Mac Retina and external screen

### ISSUE THREAD

**Issue by hb020** [KiCad/kicad-website#487]
**Both in 5.1.6:**

Application: KiCad
Version: (5.1.6-0-10_14), release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.64.1 SecureTransport (LibreSSL/2.8.3) zlib/1.2.11 nghttp2/1.39.2
Platform: macOS Catalina Version 10.15.4 (Build 19E287), 64 bit, Little endian, wxMac
Build Info:
    wxWidgets: 3.0.4 (wchar_t,STL containers,compatible with 2.8)
    Boost: 1.72.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.54.0
    Compiler: Clang 9.0.0 with C++ ABI 1002

Build settings:
    USE_WX_GRAPHICS_CONTEXT=ON
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=OFF
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

**and nightly:**
Application: KiCad
Version: (5.99.0-1660-gc6adfa40e), debug build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.64.1 SecureTransport (LibreSSL/2.8.3) zlib/1.2.11 nghttp2/1.39.2
Platform: macOS Catalina Version 10.15.4 (Build 19E287), 64 bit, Little endian, wxMac
Build Info:
    Build date: May 13 2020 03:36:08
    wxWidgets: 3.0.4 (wchar_t,STL containers,compatible with 2.8)
    Boost: 1.72.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.54.0
    Compiler: Clang 9.0.0 with C++ ABI 1002

Build settings:
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=OFF
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON
    KICAD_STDLIB_DEBUG=OFF
    KICAD_STDLIB_LIGHT_DEBUG=OFF
    KICAD_SANITIZE=OFF

With external screen.

I imagine this is related to #474 

**Symptoms:**
when moving any pcb or schema from one screen to another, the scaling is correct, but 
1. the cursor is offset. Click actions are on the crosshair position, not the mouse position (as can be expected). 
1. the scrollbars disappear

Not only is this disturbing, but also a section of the screen can no longer be used: when the mouse is in the lower part of the window or outside the window, the crosshairs remain immobile, well above the lower edge of the canvas.

Gerbview does not have this issue.

**Workaround:**

Just resize the window. It all resets, and works OK afterwards.

**Details of symptoms:**

- x position is good, the y position is off by about an inch, no matter the zoom level. The offset seems to be equal to distance between the outside lower edge of the window to the lower edge of the canvas, including the height of the scrollbar that should have been shown.
- When moving back to the original screen, the cursor remains offset. Moving multiple times does not increase the offset.
- When initially starting on retina and moving to external, the crosshairs are higher on screen than the mouse. When initially starting on external screen and moving to retina, the crosshairs are lower on screen than the mouse.
- When hovering the mouse over the menu buttons, there is no offset.
- The configuration of the arrangement of the displays (external screen above, or external screen to the side) has no influence.

The behaviour between 5.1.6 and nightly seems slightly different (in PCB scaling is also bad before the resize), but this may be related to initial window sizes. The cure is identical, so I have not persued this much further.

See attached screenshot (started on retina, moved to external). 
![Screenshot 2020-05-17 at 08 12 04](https://user-images.githubusercontent.com/12572422/82137552-a2bb2700-9819-11ea-9b7f-8dc04956bcc8.png)

**Comment by marekr** [comment]
This is not the bug report forum for kicad as indicated on the contribution guidelines.

Post issues here:
https://gitlab.com/kicad/code/kicad/-/issues

**Comment by hb020** [comment]
oops, indeed, this is for the website. Sorry.
