### ISSUE TITLE
File format documentation link is broken

### ISSUE THREAD

**Issue by johnthagen** [KiCad/kicad-website#493]
On this page: https://kicad-pcb.org/help/file-formats/

> The .sch, .lib, .brd, .kicad_pcb and .kicad_wks file formats are [specified in this PDF](https://bazaar.launchpad.net/~stambaughw/kicad/doc-read-only/view/head:/doc/help/file_formats/file_formats.pdf) (click on "download file"). The other file format documentation is Work In Progress.

Clicking on the link and then on "download file" returns:

> Not Found
The resource could not be found.

**Comment by marekr** [comment]
Fixed, the file is available from the website directly now.
Sorry if it this is a bit late.

**Comment by johnthagen** [comment]
@marekr Thanks! The page lists new documentation as WIP. Could a link be added to where this is being worked on?

**Comment by marekr** [comment]
@johnthagen Well, it should be reworded as "todo item", there's one google docs file that's already out of date but nobody has taken the effort to document it in the main repo.
