### ISSUE TITLE
"Submit a Project" is somehow inserted into the "Made With KiCad" section.

### ISSUE THREAD

**Issue by Werni2A** [KiCad/kicad-website#499]
There seems to be some bug on [https://kicad-pcb.org/made-with-kicad/page/4/](https://kicad-pcb.org/made-with-kicad/page/4/). It shows the example project from "Submit a Project" as first item. This happens only on page 4 of the "Made with KiCad" section.

**Comment by marekr** [comment]
Thanks for letting us know
