### ISSUE TITLE
Add Graphic Poligon or graphic line not working

### ISSUE THREAD

**Issue by robertoelisanc** [KiCad/kicad-website#500]
[Cargador 12V.zip](https://github.com/KiCad/kicad-website/files/4907923/Cargador.12V.zip)
# KiCad **WEBSITE** issue guidance.

Thanks for opening an issue. We accept both suggestions and bugs :D

This issue tracker is **ONLY** used for issues/suggestions with the KiCad **WEBSITE** including the KLC.

KiCad application related issues should go here: [gitlab](https://gitlab.com/kicad/code/kicad/issues)
KiCad documentation content related issues should go here: [kicad-doc](https://github.com/KiCad/kicad-doc)
KiCad documentation website related issues should go here: [kicad-doc-website](https://github.com/KiCad/kicad-doc-website)

**Comment by marekr** [comment]
> KiCad application related issues should go here: [gitlab](https://gitlab.com/kicad/code/kicad/issues)
