### ISSUE TITLE
Blog header is applied to all top level pages

### ISSUE THREAD

**Issue by Caerbannog** [KiCad/kicad-website#6]
The following page can be accessed by clicking on the breadcrumbs of an article inside "Discover" :
http://test.kicad-pcb.org/discover/

The blog header is inadequate (`This is a listing of the blog posts. Don't expect...`), and the page might lack value.

**Comment by marekr** [comment]
Yea Nick altered the _default template when he should have made a section template which overrides _default

**Comment by nickoe** [comment]
Ohh, that was it, i know it was uncomitted in my workspace for a reason
before I comitteded it.
Den 20/08/2015 20.10 skrev "Marek Roszko" <notifications@github.com>:

**Comment by marekr** [comment]
That header has been made specific to the blog section

**Comment by Caerbannog** [comment]
This issue is resolved and can be closed.
