### ISSUE TITLE
http://kicad-pcb.org/contribute/developers/

### ISSUE THREAD

**Issue by stoth** [KiCad/kicad-website#67]
According to the instructions on
http://kicad-pcb.org/contribute/developers/
1) you download the kicad source and create a feature branch
2) Before you create the patch you do an update of the "master" branch "kicad" 
and then update your featur-branch with "bzr merge ../kicad" (oarund the middle of the home page)
next command is "bzr diff > feature.patch" 

however if you follow the instructions straight from the homepage "bzr diff" would not generate 
anything (it is already committed)

My suggestion (to be consistent to the instructions och creatign a feature branch and the update/commits) is to change 

"bzr diff > feature.patch" 
into 
"bzr diff --old ../kicad > feature.patch"

**Comment by marekr** [comment]
@nickoe Any clue? I don't use bzr
