### ISSUE TITLE
Death link of GUI Translation HOWTO

### ISSUE THREAD

**Issue by LordBlick** [KiCad/kicad-website#69]
http://ci.kicad-pcb.org/job/any-kicad-doc-head/lastSuccessfulBuild/artifact/src/GUI_Translation_HOWTO/GUI_Translation_HOWTO.html
Referring page:
http://kicad-pcb.org/contribute/developers/

**Comment by nickoe** [comment]
Mmm, working on it. I accidently deleted the job on Jenkins, but it is rebuilding now.

**Comment by LordBlick** [comment]
Temporary it might be https://github.com/KiCad/kicad-source-mirror/blob/master/Documentation/GUI_Translation_HOWTO.pdf ;)
