### ISSUE TITLE
Need to add KiCad documentation license as reference

### ISSUE THREAD

**Issue by marekr** [KiCad/kicad-website#77]
The kicad-doc repo links (https://github.com/KiCad/kicad-doc/blob/master/LICENSE.adoc) to kicad-pcb.org as the source to find the license. Obviously we don't have it

Will add this tonight probably..

@nickoe

**Comment by nickoe** [comment]
Thank your for thaking care of this.

**Comment by marekr** [comment]
http://kicad-pcb.org/about/licenses/

could maybe use some more wording but the base is there
