### ISSUE TITLE
Licensing addition - need agreement

### ISSUE THREAD

**Issue by marekr** [KiCad/kicad-website#78]
We need to license the website to match the kicad documentation. 
https://github.com/KiCad/kicad-doc

This means it will be under dual license of GNU General Public License (http://www.gnu.org/licenses/gpl.html) version 3 or later, and the Creative Commons Attribution License (http://creativecommons.org/licenses/by/3.0/).

Please reply to this github issue that you approve of licensing your
contribution(s) to the website repository as such. Otherwise (hopefully not) we'll have to remove them.

@nickoe :white_check_mark:
@Caerbannog  :white_check_mark:
@reportingsjr :white_check_mark:
@orsonmmz :white_check_mark:
@adamwolf :white_check_mark:
@rdmitry :white_check_mark:
@mithro  :white_check_mark:
@ataffanel :white_check_mark:
@mattvenn :white_check_mark:
@jemtech :white_check_mark:
@Thor-Arne :white_check_mark: (via email)
@cpavlina :white_check_mark:
@tfboy :question:
@OnkartGromt :white_check_mark:
@mangelajo :question:
@marcos-paltatech :white_check_mark:
@ricardocrudo :white_check_mark:

**Comment by mattvenn** [comment]
I approve

On 14 October 2015 at 20:03, Marek Roszko <notifications@github.com> wrote:

> We need to license the website to match the kicad documentation.
> https://github.com/KiCad/kicad-doc
>
> This means it will be under dual license of GNU General Public License (
> http://www.gnu.org/licenses/gpl.html) version 3 or later, and the
> Creative Commons Attribution License (
> http://creativecommons.org/licenses/by/3.0/).
>
> Please reply to this github issue that you approve of licensing your
> contribution(s) to the website repository as such. Otherwise (hopefully
> not) we'll have to remove them.
>
> @nickoe <https://github.com/nickoe>
> @Caerbannog <https://github.com/Caerbannog>
> @reportingsjr <https://github.com/reportingsjr>
> @orsonmmz <https://github.com/orsonmmz>
> @adamwolf <https://github.com/adamwolf>
> @rdmitry <https://github.com/rdmitry>
> @mithro <https://github.com/mithro>
> @ataffanel <https://github.com/ataffanel>
> @mattvenn <https://github.com/mattvenn>
> @jemtech <https://github.com/jemtech>
> @Thor-Arne <https://github.com/Thor-Arne>
> @cpavlina <https://github.com/cpavlina>
> @tfboy <https://github.com/tfboy>
> @OnkartGromt <https://github.com/OnkartGromt>
> @mangelajo <https://github.com/mangelajo>
> @marcos-paltatech <https://github.com/marcos-paltatech>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-website/issues/78>.
>



-- 
Matthew Venn
mattvenn.net

**Comment by adamwolf** [comment]
Approved.

**Comment by nickoe** [comment]
I approve

**Comment by marcos-paltatech** [comment]
I approve

**Comment by rdmitry** [comment]
I approve

**Comment by cpavlina** [comment]
Approved

**Comment by ataffanel** [comment]
I approve

**Comment by orsonmmz** [comment]
Sure, I approve.

**Comment by marekr** [comment]
Also need
@ricardocrudo 

to approve.

**Comment by reportingsjr** [comment]
Approved

**Comment by mithro** [comment]
Approved

**Comment by ricardocrudo** [comment]
Approved

**Comment by Caerbannog** [comment]
Approved

**Comment by OnkartGromt** [comment]
Approved

**Comment by jemtech** [comment]
I approve

**Comment by marekr** [comment]
License was applied. Just @tfboy  @mangelajo missing from the approval of relicensing but their commits were minor changes so eh.
