### ISSUE TITLE
Documentation links aren't explicit about the purpose of KiCad programs

### ISSUE THREAD

**Issue by Caerbannog** [KiCad/kicad-website#8]
I figure that a newcomer wouldn't understand what "PL Editor" (or others) is from reading the following page: 
http://test.kicad-pcb.org/help/documentation/

I admit that the information is in KiCad General.

**Comment by marekr** [comment]
On one hand you wouldn't be looking for documentation until you open KiCad and go "wtf is Pl Editor" as its namedthat. I won't lie, I didn't know what it was until recently LOL.

Yea we can add a short descriptive text in there under each header. Not that it'll help if one sees Pl Editor on another page as a newbie.

**Comment by marekr** [comment]
Added one liners.

**Comment by Caerbannog** [comment]
Now the same can be said of the entries in the "Discover" menu. It's sad, because I really like how the old feature page is now spllit between Eeschema, PcbNew, ...

BTW, the "Download" menu could be renamed to "Install" to reflect that some platform just contain commands to copy and paste.

**Comment by marekr** [comment]
Yea "Install" vs "Download" is a terminology thing. You don't really see "Install" as the term though often so I thought it best to use the common word. Plus those other platform commands...still cause it to download...heh.
