### ISSUE TITLE
adopt rules for "made with kicad" projects to provide source files?

### ISSUE THREAD

**Issue by marekr** [KiCad/kicad-website#85]
@nickoe 

We have a few made with kicad projects that don't provide kicad source files or any source files really. At a minimum I say gerbers should be available. We should probably define this as policy.

Projects:
CSEduino (i swear there was something before, now theres no 0 reference to kicad and no of course no files) 
Crazyflie, it appears no actual source files are shared for kicad, just printed PDFs. I don't even think Gerbers are avaliable. Even their "kicad library" page on their wiki is blank.
EITI: No source files, looks like commerical page now.
Electrosmart: no source files

@stambaughw

**Comment by easyw** [comment]
Hi,
to be honest the guys at Crazyflie do share their kicad artworks, other-ways I couldn't have converted to 3D model the Crazyflie copter kicad board:
https://kicad-info.s3-us-west-2.amazonaws.com/original/1X/d0bbf1d92af6ed3444bed3846b4d2d4797ecb52c.png

@nickoe <https://github.com/nickoe>
here you can file the files
https://github.com/bitcraze/crazyflie-electronics/tree/master/ecad
https://raw.githubusercontent.com/bitcraze/crazyflie-electronics/master/ecad/Crazyflie%20contol%20board.kicad_pcb
and here some mechanical parts that I used for the 3D ECAD MCAD collaboration
https://github.com/bitcraze/bitcraze-mechanics

I used all my 3D mechanical models 90% script generated
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator and some directly converted from 3D STEP model to VRML using my kicad StepUp approach to obtain the following 3D results:
https://lists.launchpad.net/kicad-developers/pngI3PitrqHwK.png
https://lists.launchpad.net/kicad-developers/jpgAmBfJgBnTO.jpg

Maurice

**Comment by marekr** [comment]
Those are crazyfile 1.0 files, the made with kicad is supposedly the "2.0".

**Comment by easyw** [comment]
they did realize 1.0 and 2.0
so made with kicad sources are complaint

**Comment by marekr** [comment]
But where are the 2.0 files? I can only find PDFs. That's my entire problem. I want people who are looking for them to find them easily, not dig through the website.

**Comment by easyw** [comment]
the best is asking to https://www.bitcraze.io/ people...
they are friendly guys but ...
are you thinking to change the topic to 
**"adopt rules for "made with kicad" projects to provide most recent releases source files (all versions needed)?"**
you would loose most of boards...
moreover I would focus on remove *Eagle boards* from 'made with kicad' web page:
http://smoothieware.org/ 
http://smoothieware.org/smoothieboard
https://raw.githubusercontent.com/Smoothieware/Smoothieboard/master/smoothieboard-5driver.brd
the board is done in Eagle 
eagle version="6.3"
:)

**Comment by stambaughw** [comment]
I'm OK with that.  If there is no way confirm that the board was made
with kicad then it should not be on the made with kicad page.  If we
have boards that where made with Eagle, they need removed from the made
with kicad page.

**Comment by marekr** [comment]
Not sure where Smoothieboard came from as I didn't include it. But it needs to be removed from what it appears. @nickoe, didn't you add it?


@ataffanel, you submitted Crazyflie 2.0 to made with kicad, do you have a link available to the kicad files? Right now the bitcraze websites make it very difficult to find them if they do exist. I couldn't even find a direct link on the website to the 1.0 files.

**Comment by easyw** [comment]
most devs just put their files on github...
https://github.com/bitcraze
then you get all file list

**Comment by easyw** [comment]
may be you can consider to add a link to dev's site and a link to kicad's files on web page

**Comment by ataffanel** [comment]
As pointed-out by @easyw the way to access our source codes is through the github link. I take the input though, we should maybe add a more clear links to a list of project ordered by type.

We have not gotten around to publish the design for Crazyflie2 yet. But this is something we are going to do.

As for the ticket I do not really understand the intent: KiCad can be used for any project open or close, it might be good to show both kind of project. If you want to focus the list on open project having the kicad file available is the best to showcase how kicad is used (so that people can open existing boards as example), having only the gerber files available is not so useful.

**Comment by stambaughw** [comment]
I like this idea.  Make life easier for users so they don't have to
spend a lot of time trying to find the project files.

**Comment by easyw** [comment]
@ataffanel I really do agree so much...
moreover, people using kicad also for close/business design will be happy to know that a lot of complex boards, open or close project, has been done with kicad...
that will give kicad a robust reputation that it deserves, but that is not well known around external ECAD forums...
to be honest I switched to kicad when I found hackrf-one board ... the first time I had a lot of crashes with the dev release, so I stayed on 4022 stable one, less performing, but more reliable ... 
I just developed a realistic 3D version of 4022 stable release on sourceforge before the actual one was existing/working
I remember one time, lot of time ago, that a crash on dev release just cleaned up all my .kicad_pcb files and backup file was null either.. so I was quite afraid to switch, but now it seems to me the recent dev version is quite rock solid! and all those complex and nice boards make me an happy kicad's user/dev
 :)

**Comment by marekr** [comment]
>I like this idea.  Make life easier for users so they don't have to
>spend a lot of time trying to find the project files.

I was considering just doing that for the Crazyflies project because out of all them, they are the only ones where the files are really not easy to find.


@ataffanel 
I only threw gerber out as a suggestion, on the developer list Wayne threw out this on the mailing list:

>Open (by license) Hardware Projects:
>
>Minimum: The board file can be downloaded so that it can be modified.
>Preferred: The entire project should be made available for download and
>KiCad should be mentioned on the project website.
>
>Commercial Products:
>Minimum: KiCad mentioned on product website or donations made to project.
>
>
>For commercial products, they should directly mention that they used
>KiCad to design their product or donate to KiCad via CERN.  Otherwise,
>we are giving them free advertisement which doesn't make any sense.  I
>don't think it's unfair to ask a commercial project to mention us if
>they want us to mention them.


And in this regard I fully agree with Wayne.


Also I am not targeting Crazyflies or anything here, simply trying to get clarification on the submissions as I want to clean it up.

**Comment by nickoe** [comment]
Hi all

I think it is a good idea to compose some guide lines. I do not think we should disallow closed source projects. But I think we should try to also link the source files and the project description page for projects that are truely open. An example is the USB amroy, where the button links to the project description page but have a text link to the place to download the files.

I also like some diversity in the kind of projects that use KiCad, as we have now we hame some high density boards and some very low density "beginner" hobbyist projects show cased.

I am ok with requireing comercial projects to mention that KiCad was used.

**Comment by nickoe** [comment]
@marekr In regard to the smoothieware board. It is correct that it is an errornous image showing the smoothieboard, that is v1 which is made in eagle, but they also have a v2 which is made in kicad. https://plus.google.com/+ArthurWolf/posts/MEPqaThEaRq?pid=6109126620310037906&oid=111270782037537707264

**Comment by stambaughw** [comment]
On 11/2/2015 5:42 PM, nickoe wrote:
> Hi all
> 
> I think it is a good idea to compose some guide lines. I do not think we
> should disallow closed source projects. But I think we should try to
> also link the source files and the project description page for projects
> that are truely open. An example is the USB amroy, where the button
> links to the project description page but have a text link to the place
> to download the files.

I don't think anyone is suggesting we disallow proprietary products.
Without the project files, how do we confirm that they are indeed made
with kicad?  If they are truly made with kicad, then they should have no
issue with stating this on their website with a link to kicad.  We would
return the favor by adding them to the made with kicad page.  The other
option is for them to donate via CERN.  This way we know they are
interested in the kicad project.  That would even get them a slot on the
corporate supporters page.  It would be trivially easy to claim a board
was designed with kicad when it wasn't.  Users would come to the kicad
website and believe that these products were indeed designed with kicad
which could influence the users decision to purchase said product.  That
would be really embarrassing for the kicad project if that happened.

**Comment by stambaughw** [comment]
Would someone please add my requirements for a project being added to
the top of the "made with kicad" page so there is no confusion about
what projects can be added.  Feel free to make them more web page layout
friendly.  Please fix the title of the "Made with kicad" page (it should
be KiCad, not kicad) and make sure that all of the current projects meet
the criteria.  Also, consider adding a second blue link button "View
Files" to link to the project files for the open hardware projects.

Thanks,

Wayne

**Comment by marekr** [comment]
Committed 1d79dd9 with contributing guide lines for the section

**Comment by marekr** [comment]
@stambaughw 
http://i.imgur.com/0lXwx34.png.

Man I love anything that isn't bzr/launchpad :P Automatically puts up the message and link to the contributing guideliens.

**Comment by marekr** [comment]
@stambaughw side thought, how does a person prove they donated to CERN for their commerical product?

**Comment by marekr** [comment]
@nickoe smoothieboard v2 is not avaliable anywhere for public download or use. I would remove it for now.

**Comment by nickoe** [comment]
@marekr and @stambaughw, I will not only let people who donated via CERN have the opportunity. Some people decide to use their paid time for developing KiCad.
@marekr I guess we should remove it because there are no project files available and it is not obvious that the v2 is made in KiCad together with the description of v2 being hard to find.

**Comment by marekr** [comment]
@nickoe @stambaughw I am not against what Nick said if they contributed paid developer time, that is supporting it. I don't think any really do besides CERN but yea no reason not to allow that.

**Comment by stambaughw** [comment]
I'm fine with that as long as the developer who was paid takes the
responsibility.  Currently, I'm not aware of any paid contributions
other than through CERN.

**Comment by marekr** [comment]
@nickoe I can't find any reference to kicad or board files for GH60 which I believe you added

**Comment by stambaughw** [comment]
CERN has directly requested that we add donation contributors to the
"Corporate Supporters" section of the "About KiCad" page.  I was doing
it on the old website and will pass along any new contributors when I
get a request from CERN.

**Comment by nickoe** [comment]
@marekr  about the GH60 board, there are gerbers available and the schematic is there in pdf form on the site linked from the entry. I don't see the kicad sources, but it is clear from the gerbers and the schematic it is made in KiCad.
