### ISSUE TITLE
paltatech eiti and ecg need to meet new guidelines or be removed

### ISSUE THREAD

**Issue by marekr** [KiCad/kicad-website#86]
@marcos-paltatech 

Per the new guidelines, projects must now meet one of the requirements in the contributing guidelines:
https://github.com/KiCad/kicad-website/blob/master/CONTRIBUTING.adoc

Unfortunately neither of the EITI  or ECG project pages meet this requirement visibly. If you wish for the projects to remain and the products are commerical, meeting the requirement of a link back to KiCad is enough.

**Comment by nitrousnrg** [comment]
Thats not a problem, give me around a week so our web guy put a mention to kicad in the webpage

**Comment by nitrousnrg** [comment]
Link added on both projects webpages

**Comment by marekr** [comment]
Thanks.
